<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251208104140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE loan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start DATE NOT NULL, end_loan DATE NOT NULL, utilisateur_id INT DEFAULT NULL, item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5D30D03FB88E14F ON loan (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_C5D30D03126F525E ON loan (item_id)');
        $this->addSql('ALTER TABLE loan ADD CONSTRAINT FK_C5D30D03FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE loan ADD CONSTRAINT FK_C5D30D03126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE loan DROP CONSTRAINT FK_C5D30D03FB88E14F');
        $this->addSql('ALTER TABLE loan DROP CONSTRAINT FK_C5D30D03126F525E');
        $this->addSql('DROP TABLE loan');
    }
}
